name: release
on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: mkdir .release-artifacts && cp $(bazel cquery --output=files '(target-determinator:all  + driver:all)' 2>&1 | grep '.*/[^/]*\.[*/]*' | grep -v '\.a$') .release-artifacts/
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: .release-artifacts/*
          prerelease: true
          generate_release_notes: true
